# 1. Install and Import Dependencies

In [1]:
!pip3 install torch torchvision torchaudio

You should consider upgrading via the 'C:\Users\Gulshan\anaconda3\python.exe -m pip install --upgrade pip' command.


In [ ]:
# https://pytorch.org/

In [2]:
!pip install transformers requests beautifulsoup4 pandas numpy

You should consider upgrading via the 'C:\Users\Gulshan\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re

from transformers import AutoTokenizer, AutoModelForSequenceClassification:
This line imports classes from the transformers library,
which is used for working with pre-trained models in natural language processing tasks like text classification, 
translation, and more.

AutoTokenizer: This class is used for loading tokenizers for various pre-trained models.
AutoModelForSequenceClassification: This class is used for loading pre-trained models designed 
for sequence classification tasks.
import torch:
This line imports the torch library, which is the PyTorch deep learning framework. It provides tools 
for building and training neural networks.

import requests:
This line imports the requests library, which is used to make HTTP requests to web servers. 
It's commonly used to retrieve data from URLs.

from bs4 import BeautifulSoup:
This line imports the BeautifulSoup class from the bs4 (Beautiful Soup 4) library. 
Beautiful Soup is a library used for web scraping and parsing HTML documents.

import re:
This line imports the built-in re module, which provides support for regular expressions. 
Regular expressions are used for pattern matching and manipulation of strings.

# 2. Instantiate Model

In [5]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

C:\Users\Gulshan\anaconda3\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Gulshan\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


The AutoTokenizer class is a part of the transformers library, which is used for working with pre-trained models in natural language processing. Specifically, the AutoTokenizer class is designed to load tokenizers for various pre-trained models. Let's explore its purpose and functionality:

Purpose of AutoTokenizer:
Tokenization is the process of splitting text into individual words or subwords, which are often referred to as "tokens." Tokenization is a crucial step in natural language processing tasks as it converts raw text into a format that machine learning models can understand and process.

The AutoTokenizer class simplifies the process of loading tokenizers for specific pre-trained models. It automatically selects the appropriate tokenizer based on the model architecture or type specified in its arguments.

Key Features and Methods:

AutoTokenizer.from_pretrained(model_identifier): This static method is used to load a tokenizer for a specific pre-trained model. The model_identifier parameter is a string that represents the model's identifier or name. It can be a model name from the Hugging Face Model Hub or a local path to a model directory.

In [6]:
model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

The AutoModelForSequenceClassification class is a component of the transformers library, designed to facilitate working with pre-trained models for sequence classification tasks. Let's delve into its purpose and functionality:

Purpose of AutoModelForSequenceClassification:
Sequence classification is a type of natural language processing task where the goal is to classify a sequence of text (such as a sentence or a document) into one or more predefined categories or classes. This could involve sentiment analysis, topic categorization, intent recognition, and more.

The AutoModelForSequenceClassification class simplifies the process of loading pre-trained models that are specifically designed for sequence classification tasks.

Key Features and Methods:

AutoModelForSequenceClassification.from_pretrained(model_identifier): This static method is used to load a pre-trained model for sequence classification. The model_identifier parameter is a string that represents the model's identifier or name. It can be a model name from the Hugging Face Model Hub or a local path to a model directory.

Once you have a model instance, you can use its methods to perform inference on sequences, make predictions, and fine-tune the model for specific tasks.

# 3. Encode and Calculate Sentiment

In [7]:
tokens1 = tokenizer.encode('It was good but couldve been better. Great', return_tensors='pt')

In [8]:
tokens1

tensor([[  101, 10197, 10140, 12050, 10502, 12296, 10598, 10662, 16197,   119,
         11838,   102]])

Tokenizer:
Imagine a tool that can turn sentences into special codes. This tool is the "tokenizer." You might have made it using the AutoTokenizer tool from the transformers toolbox.

Encode:
The "encode" action is like translating a sentence into a secret language that the computer understands. For instance, the sentence "It was good but could've been better. Great" becomes a series of special numbers (token IDs) that the computer can work with.

return_tensors='pt':
Think of this as a preference you're telling the computer. You're saying, "Please give me these special numbers in a format that the PyTorch toolbox understands (PyTorch tensors). If you don't tell me this, you'll get the numbers in a different form, like a list.

Result:
The outcome of the code line (which is stored in the "tokens" box) is a set of special numbers (PyTorch tensors). Each number represents a word or part of a word from your original sentence. You can think of these numbers as a secret code that you can give to a pre-trained model. This model will then use these codes to understand the meaning of your sentence, like figuring out if the sentence is positive or negative.

So, in simple terms, this line of code helps you turn a sentence into a code that a computer model can understand and use to understand your text's meaning.

In [11]:
tokenizer.decode(tokens1[0])
#we are using the [0] index so that we can pass through list of lists

'[CLS] it was good but couldve been better. great [SEP]'

In [12]:
result1 = model(tokens1)

In [14]:
result1

SequenceClassifierOutput(loss=None, logits=tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [13]:
result1.logits

tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward0>)

In [16]:
int(torch.argmax(result.logits))+1
#got ethe rating as 4

4

In [17]:
tokens2 = tokenizer.encode('Meh, it was okay', return_tensors='pt')
tokenizer.decode(tokens2[0])
result2 = model(tokens2)

In [18]:
result2

SequenceClassifierOutput(loss=None, logits=tensor([[-0.9936,  1.6286,  2.9420, -0.1614, -2.8794]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [19]:
result2.logits

tensor([[-0.9936,  1.6286,  2.9420, -0.1614, -2.8794]],
       grad_fn=<AddmmBackward0>)

In [21]:
int(torch.argmax(result2.logits))+1
#got ethe rating as 3

3

# 4. Collect Reviews

In [23]:
r = requests.get('https://www.yelp.com/biz/social-brew-cafe-pyrmont')
soup = BeautifulSoup(r.text, 'html.parser')
regex = re.compile('.*comment.*')
results = soup.find_all('p', {'class':regex})
reviews = [result.text for result in results]

This code uses the requests, BeautifulSoup, and re libraries to scrape and extract text data from a Yelp web page. Let's break down each step:

r = requests.get('https://www.yelp.com/biz/social-brew-cafe-pyrmont'):
This line sends an HTTP GET request to the URL 'https://www.yelp.com/biz/social-brew-cafe-pyrmont' using the requests.get() function. The response from the server is stored in the variable r.

soup = BeautifulSoup(r.text, 'html.parser'):
This line creates a BeautifulSoup object named soup to parse the HTML content of the web page. The r.text part of the code extracts the HTML content from the response, and 'html.parser' specifies the parser to be used for parsing the HTML.

regex = re.compile('.*comment.*'):
This line compiles a regular expression pattern using the re.compile() function. The pattern .*comment.* is used to match any text that contains the word "comment" in it.

results = soup.find_all('p', {'class': regex}):
This line uses the find_all() method of the soup object to find all <p> (paragraph) HTML elements with a class attribute that matches the regular expression pattern. In this case, it's looking for elements with class names that contain the word "comment." The matched elements are stored in the results list.

reviews = [result.text for result in results]:
This line creates a list comprehension that iterates through the results list, which contains the matched HTML elements. For each element, it extracts the text content using the .text attribute and adds it to the reviews list. This effectively collects the text content of the comments found on the web page.


In [27]:
results[0].text

'Some of the best Milkshakes me and my daughter ever tasted. MMMMMM HMMMMMMMM.'

In [28]:
reviews

['Some of the best Milkshakes me and my daughter ever tasted. MMMMMM HMMMMMMMM.',
 "Six of us met here for breakfast before our walk to Manly. We were enjoying visiting with each other so much that I apologize for not taking any photos. We all enjoyed our food, as well as our coffee and tea drinks.We were greeted immediately by a friendly server asking if we would like to sit inside or out. We said we would like inside, but weren't exactly sure how many were joining us yet- at least 4. We were told this was no problem, the more the merrier. A few minutes later when 4 more joined our party and we explained to the server we had 6, he just quickly switched our table. I really enjoyed my serenity tea, just what I needed after a long flight in from Sfo that morning. Everyone else were more interested in the lattes for expresso drinks. All said they were hot and delicious. 2 of us ordered the avo on toast. So yummy with the beetroot... I will start adding this to mine now at home, and have f

# 5. Load Reviews into DataFrame and Score

In [29]:
import numpy as np
import pandas as pd

In [30]:
df = pd.DataFrame(np.array(reviews), columns=['review'])

In [31]:
df['review'].iloc[0]

'Some of the best Milkshakes me and my daughter ever tasted. MMMMMM HMMMMMMMM.'

In [32]:
def sentiment_score(review):
    tokens = tokenizer.encode(review, return_tensors='pt')
    result = model(tokens)
    return int(torch.argmax(result.logits))+1

In [33]:
sentiment_score(df['review'].iloc[1])

4

In [37]:
df['sentiment'] = df['review'].apply(lambda x: sentiment_score(x[:512]))
#nlp has limited the number of tokens equal to 512 thats why we are using [:512]

In [35]:
df

review  sentiment
0  Some of the best Milkshakes me and my daughter...          5
1  Six of us met here for breakfast before our wa...          4
2  Great place with delicious food and friendly s...          5
3  Great food amazing coffee and tea. Short walk ...          5
4  It was ok. Had coffee with my friends. I'm new...          3
5  Ricotta hot cakes! These were so yummy. I ate ...          5
6  Great staff and food.  Must try is the pan fri...          5
7  We came for brunch twice in our week-long visi...          4
8  I came to Social brew cafe for brunch while ex...          5
9  It was ok. The coffee wasn't the best but it w...          3

In [36]:
df['review'].iloc[3]

'Great food amazing coffee and tea. Short walk from the harbor. Staff was very friendly'